using System.Diagnostics;
using System.Text;
using System.Text.Json;
namespace LunaPC;
internal sealed class AiBrain:IDisposable
{
 const string Endpoint="http://127.0.0.1:11434/api/chat",ModelName="qwen3:4b-instruct";static readonly TimeSpan Timeout=TimeSpan.FromSeconds(90);readonly HttpClient http=new(){Timeout=Timeout};readonly SemaphoreSlim gate=new(1,1);readonly object sync=new();readonly List<ChatMessage> history=new();readonly JsonSerializerOptions json=new(){PropertyNameCaseInsensitive=true};Process? ollama;bool disposed;BrainDecision? last;record ChatMessage(string role,string content);
 const string Prompt="""
Você é LUNA, uma IA pessoal privada no Windows. Entenda linguagem natural, contexto, objetivo e planejamento. Você possui ferramentas para observar e agir.
Tipos de action: open_app, open_url, run_process, click, move_mouse, type_text, key, create_directory, copy_file, move_file, delete_file, run_powershell.
Retorne SOMENTE JSON: {"intent":"","goal":"","interpretation":"","plan":[],"assumptions":[],"relevantContext":[],"needsClarification":false,"clarificationQuestion":"","completed":false,"actions":[{"type":"","target":"","value":"","path":"","destination":"","url":"","arguments":"","x":0,"y":0,"risk":"safe"}],"response":""}
Regras: actions=[] para conversa/explicação. Para objetivos executáveis, gere o próximo passo necessário. completed=true SOMENTE quando o estado observado confirmar que o objetivo foi alcançado. Nunca invente sucesso. Escolha ações pelo significado, não por frases fixas. Se faltar informação essencial, needsClarification=true e actions=[]. Operações destrutivas e PowerShell devem usar risk=confirm. Não exponha cadeia de pensamento privada; plan/interpretation são resumos.
""";
 public AiBrain(){ }public string Model=>ModelName;public BrainDecision? LastDecision=>last;
 public async Task<string?> AskAsync(string text,CancellationToken ct=default)=>(await ThinkAsync(text,ct))?.Response;
 public async Task<BrainDecision?> ThinkAsync(string text,CancellationToken ct=default){if(disposed)throw new ObjectDisposedException(nameof(AiBrain));if(string.IsNullOrWhiteSpace(text))return null;await gate.WaitAsync(ct);try{using var timeout=CancellationTokenSource.CreateLinkedTokenSource(ct);timeout.CancelAfter(Timeout);await EnsureEngine(timeout.Token);var payload=new{model=ModelName,stream=false,keep_alive="10m",format="json",options=new{temperature=.25,num_ctx=8192},messages=Build(text)};var raw=await Send(payload,timeout.Token);var d=Parse(raw,text);if(d==null)return Fallback(text,"Não consegui estruturar meu raciocínio local agora.");lock(sync){history.Add(new ChatMessage("user",text.Trim()));history.Add(new ChatMessage("assistant",d.Response.Trim()));while(history.Count>20)history.RemoveAt(0);}last=d;return d;}catch(OperationCanceledException)when(!ct.IsCancellationRequested){return Fallback(text,"Meu cérebro local demorou mais de 90 segundos para responder.");}catch(HttpRequestException){return Fallback(text,"Meu cérebro local não está disponível. Execute a preparação da LUNA.");}catch{return Fallback(text,"Meu cérebro local encontrou um problema ao processar essa mensagem.");}finally{gate.Release();}}
 List<ChatMessage> Build(string text){lock(sync){var m=new List<ChatMessage>{new("system",Prompt)};m.AddRange(history);m.Add(new("user",text.Trim()));return m;}}
 BrainDecision? Parse(string? raw,string text){if(string.IsNullOrWhiteSpace(raw))return null;try{var d=JsonSerializer.Deserialize<BrainDecision>(raw,json);if(d==null)return null;d.Intent=Clean(d.Intent,"conversar");d.Goal=Clean(d.Goal,text);d.Interpretation=Clean(d.Interpretation,"Pedido interpretado.");d.Response=Clean(d.Response,"Entendi o que você pediu.");d.Plan??=new();d.Assumptions??=new();d.RelevantContext??=new();d.Actions??=new();foreach(var a in d.Actions){a.Type=(a.Type??"").Trim().ToLowerInvariant();a.Risk=string.IsNullOrWhiteSpace(a.Risk)?"safe":a.Risk.Trim().ToLowerInvariant();}if(d.NeedsClarification&&string.IsNullOrWhiteSpace(d.ClarificationQuestion))d.ClarificationQuestion="Pode me dar mais detalhes para eu executar isso corretamente?";return d;}catch{return new BrainDecision{Intent="conversar",Goal=text,Plan=new(){"Interpretar a mensagem","Responder"},Response=raw.Trim()};}}
 static string Clean(string? s,string f)=>string.IsNullOrWhiteSpace(s)?f:s.Trim();static BrainDecision Fallback(string t,string r)=>new(){Intent="erro_temporario",Goal=t,Plan=new(){"Tentar novamente"},Response=r};
 async Task<string?> Send(object p,CancellationToken ct){using var req=new HttpRequestMessage(HttpMethod.Post,Endpoint){Content=new StringContent(JsonSerializer.Serialize(p),Encoding.UTF8,"application/json")};using var res=await http.SendAsync(req,HttpCompletionOption.ResponseContentRead,ct);var body=await res.Content.ReadAsStringAsync(ct);if(!res.IsSuccessStatusCode)throw new HttpRequestException();using var doc=JsonDocument.Parse(body);return doc.RootElement.TryGetProperty("message",out var m)&&m.TryGetProperty("content",out var c)?c.GetString():null;}
 async Task EnsureEngine(CancellationToken ct){var u=new Uri(new Uri(Endpoint),"/");try{using var r=await http.GetAsync(u,ct);if(r.IsSuccessStatusCode)return;}catch{}var path=new[]{Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Programs","Ollama","ollama.exe"),Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles),"Ollama","ollama.exe")}.FirstOrDefault(File.Exists);if(path==null)throw new HttpRequestException();if(ollama==null||ollama.HasExited){ollama=new Process{StartInfo=new ProcessStartInfo(path,"serve"){UseShellExecute=false,CreateNoWindow=true}};ollama.Start();}for(int i=0;i<40;i++){ct.ThrowIfCancellationRequested();try{using var r=await http.GetAsync(u,ct);if(r.IsSuccessStatusCode)return;}catch{}await Task.Delay(250,ct);}throw new HttpRequestException();}
 public void ClearHistory(){lock(sync){history.Clear();last=null;}}public void Dispose(){if(disposed)return;disposed=true;try{ollama?.Dispose();}catch{}http.Dispose();gate.Dispose();}
}
