<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>LunaPC</AssemblyName>
    <RootNamespace>LunaPC</RootNamespace>
    <ApplicationIcon />
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Speech" Version="8.0.0" />
    <PackageReference Include="UIAutomationClient" Version="8.0.0" />
    <PackageReference Include="UIAutomationTypes" Version="8.0.0" />
  </ItemGroup>
</Project>
